plugins {
  id "com.gradle.develocity" version "$develocityVersion"
  id "com.gradle.common-custom-user-data-gradle-plugin" version "$customUserDataVersion"
}

def isCI = System.getenv().containsKey('CI')
def isLocal = !isCI

develocity {
  server = 'https://develocity.apache.org'
  buildScan {
    tag('grails')
    tag('grails-forge')
    publishing.onlyIf { it.authenticated }
    uploadInBackground = isLocal
  }
}

buildCache {
  local { enabled = isLocal }
  remote(develocity.buildCache) {
    push = isCI
    enabled = true
  }
}

rootProject.name = 'grails-audit-logging'

include 'plugin'
include 'examples:audit-test'
include 'examples:audit-test-allow-update-outside-transaction'
include 'examples:audit-test-hibernate7'

findProject(":plugin").name = "audit-logging"
