version = project.projectVersion
group = 'audit.test'

apply plugin: 'war'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.apache.grails.gradle.grails-web'
apply plugin: 'org.apache.grails.gradle.grails-gsp'
apply plugin: 'cloud.wondrify.asset-pipeline'

assets {
    minifyJs = true
    minifyCss = true
}

configurations {
    developmentOnly
    runtimeOnlyClasspath {
        extendsFrom developmentOnly
    }
}

dependencies {

    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    developmentOnly "org.springframework.boot:spring-boot-devtools"
    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-gsp"
    implementation "org.apache.grails:grails-sitemesh3"
    implementation "org.apache.grails:grails-data-hibernate5"

    implementation "org.apache.grails:grails-scaffolding"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    runtimeOnly "cloud.wondrify:asset-pipeline-grails"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "com.zaxxer:HikariCP"
    integrationTestImplementation testFixtures("org.apache.grails:grails-geb")
    testImplementation "org.apache.grails:grails-testing-support-datamapping"
    testImplementation "org.apache.grails:grails-testing-support-web"
    testImplementation "org.spockframework:spock-core"
    testImplementation "org.junit.platform:junit-platform-testkit" // EmbeddedSpecRunner

    implementation project(":audit-logging")
    profile "org.apache.grails.profiles:web"
}

compileJava.options.release = 21

tasks.withType(Test).configureEach { Task it ->
    useJUnitPlatform()

    if (it.name == 'test') {
        it.testLogging {
            showStandardStreams = true
            exceptionFormat = 'full'
            events = ["passed", "failed", "skipped", 'standardOut', 'standardError']
        }
    }

    if (it.name == 'integrationTest') {
        // Added to pass on audit-test.AuditTrail.datasource
        it.systemProperties += System.properties
        it.testLogging {
            showStandardStreams = true
            exceptionFormat = 'full'
            events = ["passed", "failed", "skipped", 'standardOut', 'standardError']
        }
    }
}
